### ISSUE TITLE
Tidy YAML 

### ISSUE THREAD

**Issue by nanophyto** [nanophyto/Abil#163]
Could remove (#161): 
`path_in` (not needed)

Could set these to always be estimated?
```
  reg_scoring:
   R2: r2
   MAE: neg_mean_absolute_error
   RMSE: neg_root_mean_squared_error

  clf_scoring:
   accuracy: balanced_accuracy

```
